-- Ajustes v84 — JÁ APLICADO no Supabase (migração funcao_copeiro_v84). Registro.
-- Função nova: Copeiro (Restaurante). Cuida da copa: sucos, cafés, sobremesas simples, bandejas,
-- organização e limpeza de copos/louças e apoio aos garçons.
-- Perfil ideal: constância e organização com bom trato com a equipe: D10 I20 S40 C30.
with inserido as (
  insert into public.perfis_disc (funcao, peso_d, peso_i, peso_s, peso_c, qtd_perguntas)
  select 'Copeiro', 10, 20, 40, 30, 20
  where not exists (select 1 from public.perfis_disc p where p.funcao = 'Copeiro')
  returning id
)
insert into public.perguntas_disc (perfil_disc_id, ordem, texto_pergunta, opcao_d, opcao_i, opcao_s, opcao_c)
select i.id, q.ordem, q.texto, q.d, q.i, q.s, q.c
from inserido i
cross join (values
  (1, 'No horário de pico, chegam vários pedidos de sucos e cafés ao mesmo tempo. Eu:',
   'Acelero ao máximo e despacho o mais rápido possível',
   'Aviso os garçons, brinco com a equipe e vou tocando',
   'Mantenho o ritmo e faço um pedido de cada vez, sem me perder',
   'Organizo a fila pela ordem de chegada e confiro cada comanda'),
  (2, 'Um garçom chega apressado cobrando um pedido atrasado. Eu:',
   'Respondo na hora que já está saindo e resolvo',
   'Converso com ele, acalmo e mostro que estou priorizando',
   'Continuo tranquilo e entrego assim que ficar pronto',
   'Confiro na comanda quando o pedido chegou e em que ponto está'),
  (3, 'Minha maior força trabalhando na copa é:',
   'Dar conta de muitos pedidos em pouco tempo',
   'Me entender bem com garçons e cozinha',
   'Manter o mesmo cuidado do começo ao fim do turno',
   'Deixar tudo organizado, limpo e no padrão'),
  (4, 'Sobre seguir a receita e a medida certa de cada suco, drink sem álcool ou sobremesa, eu:',
   'Sigo o principal e ajusto pra ganhar tempo',
   'Sigo, mas gosto de caprichar na apresentação',
   'Faço sempre do mesmo jeito, todos os dias',
   'Sigo à risca as medidas e o padrão da casa'),
  (5, 'Meu jeito de trabalhar é mais:',
   'Rápido e prático',
   'Comunicativo e prestativo',
   'Calmo e constante',
   'Organizado e cuidadoso'),
  (6, 'Ao chegar para o turno e encontrar a copa desorganizada, eu:',
   'Resolvo rápido o mais urgente e começo a trabalhar',
   'Chamo quem estiver por perto pra arrumarmos juntos',
   'Arrumo com calma, do jeito que sempre faço',
   'Organizo cada coisa no seu lugar e confiro o que está faltando'),
  (7, 'Um pedido saiu errado da copa e voltou da mesa. Eu:',
   'Refaço na hora, sem perder tempo',
   'Peço desculpas ao garçom e refaço com simpatia',
   'Refaço com tranquilidade, sem me abalar',
   'Vejo onde errei pra não acontecer de novo'),
  (8, 'O que mais me motiva no trabalho é:',
   'Ver os pedidos saindo rápido, sem fila',
   'O clima bom com a equipe e os elogios dos clientes',
   'Ter uma rotina estável e previsível',
   'Ver tudo sair certinho e a copa impecável'),
  (9, 'Sobre higiene de copos, louças, utensílios e da bancada, eu:',
   'Faço o necessário para não atrasar os pedidos',
   'Faço, e aviso a equipe quando vejo algo fora do lugar',
   'Mantenho a limpeza como parte da minha rotina',
   'Sigo todas as regras de higiene e confiro tudo antes de usar'),
  (10, 'Quando falta gelo, fruta ou algum insumo no meio do movimento, eu:',
   'Decido na hora uma solução e sigo em frente',
   'Aviso rápido o garçom e o gerente e combino o que fazer',
   'Mantenho a calma e uso o que tenho até chegar a reposição',
   'Anoto o que faltou para a reposição não falhar de novo'),
  (11, 'Trabalhando junto com garçons e cozinha, eu costumo:',
   'Tomar a frente quando o fluxo trava',
   'Puxar conversa e manter todo mundo animado',
   'Ajudar no que precisar, sem criar atrito',
   'Seguir o combinado sobre quem faz o quê'),
  (12, 'Quando o movimento está fraco, eu:',
   'Procuro algo para adiantar e não fico parado',
   'Aproveito para conversar e ajudar a equipe do salão',
   'Sigo minhas tarefas de rotina com calma',
   'Aproveito para limpar, repor e organizar a copa'),
  (13, 'Se o gerente muda o jeito de montar as bandejas ou servir as bebidas, eu:',
   'Aceito e já começo a fazer do jeito novo',
   'Pergunto o motivo e comento com os colegas',
   'Preciso de um tempinho, mas me adapto bem',
   'Quero entender o passo a passo certinho antes de mudar'),
  (14, 'Sobre fazer vários pedidos ao mesmo tempo, eu:',
   'Gosto, trabalho melhor na pressão',
   'Consigo, principalmente com a equipe ajudando',
   'Prefiro um de cada vez, mas dou conta',
   'Faço com uma ordem definida para não errar'),
  (15, 'Ao montar uma bandeja ou finalizar uma sobremesa, o que mais me importa é:',
   'Entregar rápido',
   'Ficar bonito para o cliente',
   'Sair sempre igual',
   'Estar correta, completa e no padrão'),
  (16, 'No fim do turno, antes de ir embora, eu:',
   'Deixo o essencial pronto e saio',
   'Passo o que aconteceu para quem vai assumir',
   'Faço a mesma rotina de fechamento de sempre',
   'Confiro limpeza, estoque e deixo tudo organizado para o próximo'),
  (17, 'Quando um colega da copa está atrasado com os pedidos, eu:',
   'Assumo parte dos pedidos para destravar',
   'Dou uma força e animo ele',
   'Ajudo com calma sem atrapalhar o que ele está fazendo',
   'Ajudo seguindo a ordem das comandas'),
  (18, 'Ao receber uma crítica sobre o meu trabalho, eu:',
   'Aceito e corrijo logo',
   'Converso para entender melhor e mostrar meu lado',
   'Escuto com calma e procuro melhorar',
   'Peço detalhes do que ficou fora do padrão'),
  (19, 'Sobre controlar o que foi usado e o que precisa repor na copa, eu:',
   'Resolvo quando falta',
   'Aviso a equipe quando percebo que está acabando',
   'Faço a conferência de sempre',
   'Controlo tudo com anotação ou lista'),
  (20, 'O que melhor me descreve na copa é:',
   'Ágil e resolvo rápido',
   'Simpático e fácil de trabalhar junto',
   'Paciente e constante',
   'Caprichoso e organizado')
) as q(ordem, texto, d, i, s, c);
