-- Ajustes v49 — JÁ APLICADOS no projeto Supabase "contrateja" (registro, e para recriar o banco do zero).

-- Funções novas: Salgadeiro e Salgadeira (Padaria e Lanchonete).
-- Perfil ideal parecido com o do Padeiro (constância e capricho): D15 I10 S35 C40.
-- Cada função recebe as mesmas 20 perguntas.
with novos(funcao) as (values ('Salgadeiro'), ('Salgadeira')),
inseridos as (
  insert into public.perfis_disc (funcao, peso_d, peso_i, peso_s, peso_c, qtd_perguntas)
  select n.funcao, 15, 10, 35, 40, 20
  from novos n
  where not exists (select 1 from public.perfis_disc p where p.funcao = n.funcao)
  returning id, funcao
)
insert into public.perguntas_disc (perfil_disc_id, ordem, texto_pergunta, opcao_d, opcao_i, opcao_s, opcao_c)
select i.id, q.ordem, q.texto, q.d, q.i, q.s, q.c
from inseridos i
cross join (values
  (1, 'Na hora de modelar coxinhas, pastéis ou risoles em grande quantidade, eu:',
   'Trabalho no ritmo mais rápido que consigo pra bater a meta',
   'Faço conversando e animando o pessoal da produção',
   'Mantenho um ritmo constante do começo ao fim',
   'Confiro o tamanho e o formato de cada um pra ficarem iguais'),
  (2, 'Se a massa do salgado não está no ponto, eu:',
   'Decido rápido o que ajustar e continuo',
   'Chamo alguém da equipe pra opinar na hora',
   'Paro com calma e refaço até acertar o ponto',
   'Volto na receita e confiro cada medida antes de corrigir'),
  (3, 'Minha maior força na produção de salgados é:',
   'Dar conta de grande volume em pouco tempo',
   'Deixar o salgado bem apresentado e o clima da equipe leve',
   'Manter a mesma qualidade todos os dias',
   'Padronizar tamanho, recheio e ponto de cozimento'),
  (4, 'Sobre seguir a quantidade exata de recheio por unidade, eu:',
   'Sigo o essencial pra não perder tempo',
   'Sigo, mas gosto de caprichar no visual',
   'Sigo com constância todos os dias',
   'Sigo à risca, medindo ou pesando cada porção'),
  (5, 'Meu estilo de trabalho na produção de salgados é mais:',
   'Rápido e prático',
   'Comunicativo e animado',
   'Constante e paciente',
   'Organizado e detalhista'),
  (6, 'Chegou uma encomenda grande de salgados pra uma festa, em cima da hora. Eu:',
   'Assumo o comando e acelero a produção',
   'Animo o time e encaro como um desafio em grupo',
   'Organizo com calma pra entregar no prazo',
   'Planejo cada etapa e a quantidade pra não faltar nem sobrar'),
  (7, 'Se uma fornada de salgados queima ou sai fora do padrão, eu:',
   'Descarto e refaço logo',
   'Levo na brincadeira e refaço',
   'Refaço com calma, sem me abalar',
   'Investigo a causa (temperatura, tempo) pra não repetir'),
  (8, 'O que mais me motiva no trabalho é:',
   'Bater a meta de produção do dia',
   'Ver o cliente elogiando o salgado',
   'Ter uma rotina estável e previsível',
   'Ver todos os salgados perfeitos e padronizados'),
  (9, 'Sobre higiene, luvas, touca e limpeza da bancada, eu:',
   'Faço o necessário sem perder tempo',
   'Faço, mas às vezes esqueço com a correria',
   'Mantenho como rotina, todos os dias',
   'Sigo todas as regras de higiene rigorosamente, sem exceção'),
  (10, 'Se pudesse escolher, eu me destacaria por:',
   'Produzir mais que todo mundo, com qualidade',
   'Ser lembrado pelo salgado gostoso e pela simpatia',
   'Nunca faltar nem falhar na produção',
   'Nunca errar o ponto, o peso ou o sabor'),
  (11, 'Prefiro aprender uma receita nova de salgado:',
   'Direto na prática, testando',
   'Conversando e vendo alguém fazer',
   'Com calma, repetindo até fixar',
   'Por escrito, com a ficha técnica completa'),
  (12, 'O que mais me incomoda no trabalho é:',
   'Lentidão e falta de decisão',
   'Ambiente frio e sem conversa',
   'Mudança brusca de rotina',
   'Desorganização e falta de padrão'),
  (13, 'Quando bate o cansaço no fim do turno, eu:',
   'Empurro até terminar tudo',
   'Uso o bom humor pra aliviar',
   'Mantenho o mesmo ritmo até o fim',
   'Sigo o checklist de fechamento até o fim'),
  (14, 'Se a chefia pede um salgado novo pro cardápio, eu:',
   'Testo rápido uma versão',
   'Empolgo e sugiro sabores diferentes',
   'Testo com calma até acertar',
   'Pesquiso e padronizo a receita com precisão antes'),
  (15, 'Meu ritmo de trabalho é:',
   'Acelerado',
   'Animado',
   'Constante',
   'Cuidadoso'),
  (16, 'Em dias de muito movimento, com pedidos e produção acumulando, eu:',
   'Assumo o controle e corro atrás',
   'Mantenho o clima leve com a equipe',
   'Sigo firme, sem me alterar',
   'Mantenho o padrão de qualidade mesmo com pressa'),
  (17, 'Se sobra tempo entre uma produção e outra, eu:',
   'Já adianto a próxima etapa',
   'Converso com a equipe',
   'Aproveito pra descansar um pouco',
   'Organizo a bancada e confiro insumos e validades'),
  (18, 'Se percebo que um recheio ou ingrediente está perto do vencimento, eu:',
   'Resolvo na hora, usando primeiro ou descartando',
   'Aviso o pessoal e vejo o que fazer juntos',
   'Sigo a rotina de usar o mais antigo primeiro',
   'Confiro a data, registro e sigo o procedimento de validade'),
  (19, 'Minha relação com repetir a mesma tarefa (ex.: enrolar centenas de salgados) é:',
   'Prefiro variar de tarefa',
   'Tudo bem, desde que dê pra conversar',
   'Não me incomoda, gosto de rotina',
   'Prefiro assim, fico mais preciso repetindo'),
  (20, 'Ao final do turno, o que mais me deixa satisfeito(a) é:',
   'Ter dado conta de toda a produção',
   'Ter deixado o time e os clientes satisfeitos',
   'Ter cumprido a produção sem sobressaltos',
   'Ter tudo padronizado, limpo e sem erro')
) as q(ordem, texto, d, i, s, c);
